### ISSUE TITLE
The set fact for create_vg has no stdout

### ISSUE THREAD

**Issue by flyemsafe** [flyemsafe/swygue-lvm#6]
Looks like the awk statement below does not return anything
```
awk '/2fdev2f{{ host_device }}
```

```
TASK [swygue-lvm : set_fact] *****************************************************************************
Sunday 25 August 2019  10:33:13 -0400 (0:00:00.065)       0:00:42.450 ********* 
fatal: [localhost]: FAILED! => {}

MSG:

The task includes an option with an undefined variable. The error was: 'dict object' has no attribute 'stdout'

The error appears to have been in '/home/admin/qubinode-installer/playbooks/roles/swygue-lvm/tasks/precheck.yml': line 36, column 3, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:


- set_fact:
  ^ here
```

**Comment by flyemsafe** [comment]
There's two create_vg set_fact statements

```
- set_fact:
    create_vg: "{{ true if pvs_info.stdout == '' and vgs_info.stdout == '' and pvs_info.stdout == '' else false }}"

- set_fact:
    current_vg: "{{ pvs_info.stdout if pvs_info.stdout != '' else 'no_vg' }}"
```
